### ISSUE TITLE
Anlegen von Einträgen

### ISSUE THREAD

**Issue by florianredmann** [timgrohmann/exWM#18]
Einträge sollen erstellt und zentral festgehalten werden.

**Eintrag**
Ein Eintrag besteht aus einer Überschrift und einem mit Markdown formatierbaren Textkörper. Sie speichern das Erstellungsdatum. Beim Erstellen gibt man Email-Adresse an um Nachricht bei Änderungen o.ä. zu erhalten.

**Comment by timgrohmann** [comment]
Zeitschätzung: 4 Stunden.
