### ISSUE TITLE
Up-/Downvoten von Einträgen

### ISSUE THREAD

**Issue by florianredmann** [timgrohmann/exWM#22]
Beiträge können mit einem "Daumen hoch" bzw. "Daumen runter" bewertet werden. Die Gesamtzahl der jeweiligen Votes wird angezeigt.

**Comment by timgrohmann** [comment]
Hierzu muss das Schema der Datenbank erweitert werden.

**Comment by timgrohmann** [comment]
Zeitschätzung: 3 Stunden.

**Comment by nicoberlaender** [comment]
Done.
