### ISSUE TITLE
Vorschlag von bereits genutzten Schlagworten

### ISSUE THREAD

**Issue by florianredmann** [timgrohmann/exWM#29]
Bereits verwendete Schlagworte, sowie die meist gewählten, werden bei der Erstellung eines Eintrages vorgeschlagen.

**Comment by felixwo** [comment]
Nicht ausgereift

Probleme:

    Es werden alle Wörter mit Großbuchstaben am Anfgang vorgeschlagen.
    Der Algorithmus sollte nur Wörter vorschlagen, die tatsächlich Sinn ergeben (Fachbegriffe und Wörter, die ansonsten in nicht vielen Entrys vorkommen)

**Comment by elsholz** [comment]
Du erwartest von dem Algorithmus, dass er nur sinnvolle Schlagworte vorschlägt? Wie soll er denn das heraus finden? Die AI ist halt nicht darauf trainiert worden, Fachspezifische Begriffe zu extrahieren, sondern nur darauf, eine Auswahl von Nomen zu liefern, die anhand der Häufigkeit und des Satzkontexts bestimmt werden.

Die Verbesserung des Algo macht Sinn, da gebe ich dir Recht! Die Erreichung dieses Ziels setzt aber noch einige weitere Punkte Voraus:
1. Die Datenbank mit vorhandenen Tags fließt in die tag suggestion ein
1. Der Algorithmus wird von vornherein auf Unternehmens spezifische Beiträge trainiert

Da dies (insbesondere Punkt 2) aber etwas komplexer ist, sollten wir uns zur Zeit mit dem zufrieden geben, was wir schon haben.

Einzig und allein Punkt 1 könnte noch kurzfristig einfließen und das vorhandene tag-selection system so ausgebaut werden, dass custom tags hinzugefügt werden können (Verbesserung UI Interface).
